<a href="https://colab.research.google.com/github/jahnaviathi7/NewcodingBot/blob/main/attendance2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving meetinglistdetails_2026_05_29_2026_05_29.csv to meetinglistdetails_2026_05_29_2026_05_29.csv
Saving meetinglistdetails_2026_05_30_2026_05_30.csv to meetinglistdetails_2026_05_30_2026_05_30.csv

In [ ]:
import os

print(os.listdir())

['.config', 'meetinglistdetails_2026_05_29_2026_05_29.csv', 'meetinglistdetails_2026_05_30_2026_05_30.csv', 'sample_data']

In [ ]:
# Install packages
!pip install pandas openpyxl scikit-learn -q

import pandas as pd
import glob
from google.colab import files
from sklearn.tree import DecisionTreeClassifier

# =====================================
# 1. Upload CSV Files
# =====================================
print("Upload both CSV files")
uploaded = files.upload()

# =====================================
# 2. Read and Merge Data
# =====================================
csv_files = glob.glob("*.csv")

print("\nUploaded Files:")
for f in csv_files:
    print(f)

df = pd.concat(
    [pd.read_csv(file) for file in csv_files],
    ignore_index=True
)

print("\nMerged Dataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
display(df.head())

# =====================================
# 3. Show Column Names
# =====================================
print("\nColumns:")
print(df.columns.tolist())

# =====================================
# 4. Attendance Calculation
# =====================================
total_meeting_minutes = (
    df.groupby("ID")["Duration (minutes)"]
      .first()
      .sum()
)

print("\nTotal Meeting Minutes:")
print(total_meeting_minutes)

attendance = (
    df.groupby(
        ["Email", "Name (original name)"]
    )["Duration (minutes).1"]
    .sum()
    .reset_index()
)

attendance["Attendance_Percentage"] = (
    attendance["Duration (minutes).1"]
    / total_meeting_minutes
) * 100

attendance["Attendance_Percentage"] = (
    attendance["Attendance_Percentage"]
    .round(2)
)

attendance["Eligibility"] = attendance[
    "Attendance_Percentage"
].apply(
    lambda x:
    "Eligible"
    if x >= 80
    else "Not Eligible"
)

# =====================================
# 5. Display Results
# =====================================
print("\nAttendance Report:")
display(attendance.head(20))

# =====================================
# 6. Eligibility Summary
# =====================================
eligible_count = (
    attendance["Eligibility"] == "Eligible"
).sum()

not_eligible_count = (
    attendance["Eligibility"] == "Not Eligible"
).sum()

print("\nEligibility Summary")
print("Eligible Candidates:", eligible_count)
print("Not Eligible Candidates:", not_eligible_count)

# =====================================
# 7. Machine Learning Model
# =====================================
attendance["Target"] = attendance[
    "Eligibility"
].map({
    "Eligible": 1,
    "Not Eligible": 0
})

X = attendance[["Attendance_Percentage"]]
y = attendance["Target"]

model = DecisionTreeClassifier(random_state=42)

model.fit(X, y)

print("\nML Model Trained Successfully")

# =====================================
# 8. Sample Prediction
# =====================================
test_values = [[75], [82], [95]]

predictions = model.predict(test_values)

print("\nPrediction Results")

for value, pred in zip(test_values, predictions):
    status = "Eligible" if pred == 1 else "Not Eligible"
    print(f"Attendance {value[0]}% --> {status}")

# =====================================
# 9. Save Excel File
# =====================================
output = attendance[
    [
        "Name (original name)",
        "Email",
        "Attendance_Percentage",
        "Eligibility"
    ]
]

excel_file = "Candidate_Eligibility_Report.xlsx"

output.to_excel(
    excel_file,
    index=False
)

print("\nExcel File Created:")
print(excel_file)

# =====================================
# 10. Show Final Output
# =====================================
print("\nFinal Report Preview:")
display(output.head(20))

# =====================================
# 11. Download Excel
# =====================================
files.download(excel_file)

Upload both CSV files

Saving meetinglistdetails_2026_05_29_2026_05_29.csv to meetinglistdetails_2026_05_29_2026_05_29 (2).csv
Saving meetinglistdetails_2026_05_30_2026_05_30.csv to meetinglistdetails_2026_05_30_2026_05_30 (2).csv

Uploaded Files:
meetinglistdetails_2026_05_29_2026_05_29 (1).csv
meetinglistdetails_2026_05_29_2026_05_29.csv
meetinglistdetails_2026_05_30_2026_05_30 (2).csv
meetinglistdetails_2026_05_30_2026_05_30.csv
meetinglistdetails_2026_05_30_2026_05_30 (1).csv
meetinglistdetails_2026_05_29_2026_05_29 (2).csv

Merged Dataset Shape:
(29577, 24)

First 5 Rows:

,Topic,Type,ID,Host name,Host email,Start time,End time,Participants,Duration (minutes),Total participant minutes,...,Max concurrent views,Creation time,Name (original name),Email,Join time,Leave time,Duration (minutes).1,Guest,Recording disclaimer response,In waiting room
0,Cloud Computing - DevOps - Summer Online Inter...,Meeting,918 0609 9436,santosh s,venkatasivasantosh.s@apssdc.in,05/29/2026 06:04:58 PM,05/29/2026 08:14:30 PM,972,130,31223,...,-,05/05/2026 02:35:03 PM,Haritha K,haritha200624@gmail.com,05/29/2026 06:19:49 PM,05/29/2026 06:22:21 PM,3,Yes,OK,No
1,Cloud Computing - DevOps - Summer Online Inter...,Meeting,918 0609 9436,santosh s,venkatasivasantosh.s@apssdc.in,05/29/2026 06:04:58 PM,05/29/2026 08:14:30 PM,972,130,31223,...,-,05/05/2026 02:35:03 PM,234M1A2559 Uppalapati Pravallika,upravallika75@gmail.com,05/29/2026 06:22:54 PM,05/29/2026 06:24:14 PM,2,Yes,No Response,No
2,Cloud Computing - DevOps - Summer Online Inter...,Meeting,918 0609 9436,santosh s,venkatasivasantosh.s@apssdc.in,05/29/2026 06:04:58 PM,05/29/2026 08:14:30 PM,972,130,31223,...,-,05/05/2026 02:35:03 PM,keerthika puttan,keerthikaputtan@gmail.com,05/29/2026 06:26:49 PM,05/29/2026 06:29:20 PM,3,Yes,OK,No
3,Cloud Computing - DevOps - Summer Online Inter...,Meeting,918 0609 9436,santosh s,venkatasivasantosh.s@apssdc.in,05/29/2026 06:04:58 PM,05/29/2026 08:14:30 PM,972,130,31223,...,-,05/05/2026 02:35:03 PM,SANDEEP DOMMETI,dommetisandeep5@gmail.com,05/29/2026 06:26:50 PM,05/29/2026 06:47:32 PM,21,Yes,No Response,No
4,Cloud Computing - DevOps - Summer Online Inter...,Meeting,918 0609 9436,santosh s,venkatasivasantosh.s@apssdc.in,05/29/2026 06:04:58 PM,05/29/2026 08:14:30 PM,972,130,31223,...,-,05/05/2026 02:35:03 PM,24B81A05P1 Mohammad faiza,mohammadfaizafanar@gmail.com,05/29/2026 06:32:46 PM,05/29/2026 07:57:13 PM,85,Yes,No Response,No

Columns:
['Topic', 'Type', 'ID', 'Host name', 'Host email', 'Start time', 'End time', 'Participants', 'Duration (minutes)', 'Total participant minutes', 'Department', 'Group', 'Source', 'Unique viewers', 'Max concurrent views', 'Creation time', 'Name (original name)', 'Email', 'Join time', 'Leave time', 'Duration (minutes).1', 'Guest', 'Recording disclaimer response', 'In waiting room']

Total Meeting Minutes:
434

Attendance Report:

,Email,Name (original name),Duration (minutes).1,Attendance_Percentage,Eligibility
0,2023csm.r119@svce.edu.in,Kannuru SethuMadhav,63,14.52,Not Eligible
1,2023eee.r145@svce.edu.in,Madibaka Vamsi-23BFA02145 ( Madibaka Vamsi ),240,55.30,Not Eligible
2,20l31a04i9@gmail.com,teja yeluri 20L31A04I9,258,59.45,Not Eligible
3,22295cm019@gmail.com,jatla anusha,240,55.30,Not Eligible
4,23221a0259@bvcgroup.in,23221A0259 Y.Anil Kumar,108,24.88,Not Eligible
5,23221a0413@bvcgroup.in,23221A0413-Appari Tulasi ( Appari Tulasi ),207,47.70,Not Eligible
6,23221a0418@bvcgroup.in,B.NAGARAJU-23221A0418 ( Nagaraju Barre ),33,7.60,Not Eligible
7,23221a0418@bvcgroup.in,Nagaraju Barre,78,17.97,Not Eligible
8,23221a0428@bvcgroup.in,Bonam Tarun Teja,45,10.37,Not Eligible
9,23221a04i9@bvcgroup.in,raja.y 23321A04i9 ( Yelisetti Bala subbaraju ),51,11.75,Not Eligible
10,23221a04j4@bvcgroup.in,MANDELA NAVEEN SAI KRISHNA _ 23221A04J4 ( MAND...,375,86.41,Eligible
11,23221a04j4@bvcgroup.in,MANDELA NAVEEN SAI KRISHNA _ 23221A04J4 ( MAND...,96,22.12,Not Eligible
12,23221a0568@bvcgroup.in,Kurasa Baby,18,4.15,Not Eligible
13,23221a4203@bvcgroup.in,Akula Jahnavi Lakshmi Pavani,267,61.52,Not Eligible
14,23221a4207@bvcgroup.in,Harshika Bokka,591,136.18,Eligible
15,23221a4213@bvcgroup.in,Durga Mallesh Chollangi,3,0.69,Not Eligible
16,23221a4216@bvcgroup.in,Leelakumar Geddada,12,2.76,Not Eligible
17,23221a4217@bvcgroup.in,23221a4217,33,7.60,Not Eligible
18,23221a4225@bvcgroup.in,Manoj Kumar,57,13.13,Not Eligible
19,23221a4231@bvcgroup.in,23221a4231@bvcgroup.in,330,76.04,Not Eligible

Eligibility Summary
Eligible Candidates: 974
Not Eligible Candidates: 2423

ML Model Trained Successfully

Prediction Results
Attendance 75% --> Not Eligible
Attendance 82% --> Eligible
Attendance 95% --> Eligible

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

Excel File Created:
Candidate_Eligibility_Report.xlsx

Final Report Preview:

,Name (original name),Email,Attendance_Percentage,Eligibility
0,Kannuru SethuMadhav,2023csm.r119@svce.edu.in,14.52,Not Eligible
1,Madibaka Vamsi-23BFA02145 ( Madibaka Vamsi ),2023eee.r145@svce.edu.in,55.30,Not Eligible
2,teja yeluri 20L31A04I9,20l31a04i9@gmail.com,59.45,Not Eligible
3,jatla anusha,22295cm019@gmail.com,55.30,Not Eligible
4,23221A0259 Y.Anil Kumar,23221a0259@bvcgroup.in,24.88,Not Eligible
5,23221A0413-Appari Tulasi ( Appari Tulasi ),23221a0413@bvcgroup.in,47.70,Not Eligible
6,B.NAGARAJU-23221A0418 ( Nagaraju Barre ),23221a0418@bvcgroup.in,7.60,Not Eligible
7,Nagaraju Barre,23221a0418@bvcgroup.in,17.97,Not Eligible
8,Bonam Tarun Teja,23221a0428@bvcgroup.in,10.37,Not Eligible
9,raja.y 23321A04i9 ( Yelisetti Bala subbaraju ),23221a04i9@bvcgroup.in,11.75,Not Eligible
10,MANDELA NAVEEN SAI KRISHNA _ 23221A04J4 ( MAND...,23221a04j4@bvcgroup.in,86.41,Eligible
11,MANDELA NAVEEN SAI KRISHNA _ 23221A04J4 ( MAND...,23221a04j4@bvcgroup.in,22.12,Not Eligible
12,Kurasa Baby,23221a0568@bvcgroup.in,4.15,Not Eligible
13,Akula Jahnavi Lakshmi Pavani,23221a4203@bvcgroup.in,61.52,Not Eligible
14,Harshika Bokka,23221a4207@bvcgroup.in,136.18,Eligible
15,Durga Mallesh Chollangi,23221a4213@bvcgroup.in,0.69,Not Eligible
16,Leelakumar Geddada,23221a4216@bvcgroup.in,2.76,Not Eligible
17,23221a4217,23221a4217@bvcgroup.in,7.60,Not Eligible
18,Manoj Kumar,23221a4225@bvcgroup.in,13.13,Not Eligible
19,23221a4231@bvcgroup.in,23221a4231@bvcgroup.in,76.04,Not Eligible